// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guvvybityqvptxjuzdtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1dnZ5Yml0eXF2cHR4anV6ZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODM0MzUsImV4cCI6MjA2MjQ1OTQzNX0.rRCEFfWoysiAp7SUpqEYulB11lVcm6ccySVP1dVXnmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);